COPY dbgen_version FROM '/tmp/dbgen_version.dat' WITH DELIMITER '|' NULL AS '';
COPY customer_address FROM '/tmp/customer_address.dat' WITH DELIMITER '|' NULL AS '';
COPY customer_demographics FROM '/tmp/customer_demographics.dat' WITH DELIMITER '|' NULL AS '';
COPY date_dim FROM '/tmp/date_dim.dat' WITH DELIMITER '|' NULL AS '';
COPY warehouse FROM '/tmp/warehouse.dat' WITH DELIMITER '|' NULL AS '';
COPY ship_mode FROM '/tmp/ship_mode.dat' WITH DELIMITER '|' NULL AS '';
COPY time_dim FROM '/tmp/time_dim.dat' WITH DELIMITER '|' NULL AS '';
COPY reason FROM '/tmp/reason.dat' WITH DELIMITER '|' NULL AS '';
COPY income_band FROM '/tmp/income_band.dat' WITH DELIMITER '|' NULL AS '';
COPY item FROM '/tmp/item.dat' WITH DELIMITER '|' NULL AS '';
COPY store FROM '/tmp/store.dat' WITH DELIMITER '|' NULL AS '';
COPY call_center FROM '/tmp/call_center.dat' WITH DELIMITER '|' NULL AS '';
COPY customer FROM '/tmp/customer.dat' WITH DELIMITER '|' NULL AS '';
COPY web_site FROM '/tmp/web_site.dat' WITH DELIMITER '|' NULL AS '';
COPY store_returns FROM '/tmp/store_returns.dat' WITH DELIMITER '|' NULL AS '';
COPY household_demographics FROM '/tmp/household_demographics.dat' WITH DELIMITER '|' NULL AS '';
COPY web_page FROM '/tmp/web_page.dat' WITH DELIMITER '|' NULL AS '';
COPY promotion FROM '/tmp/promotion.dat' WITH DELIMITER '|' NULL AS '';
COPY catalog_page FROM '/tmp/catalog_page.dat' WITH DELIMITER '|' NULL AS '';
COPY inventory FROM '/tmp/inventory.dat' WITH DELIMITER '|' NULL AS '';
COPY catalog_returns FROM '/tmp/catalog_returns.dat' WITH DELIMITER '|' NULL AS '';
COPY web_returns FROM '/tmp/web_returns.dat' WITH DELIMITER '|' NULL AS '';
COPY web_sales FROM '/tmp/web_sales.dat' WITH DELIMITER '|' NULL AS '';
COPY catalog_sales FROM '/tmp/catalog_sales.dat' WITH DELIMITER '|' NULL AS '';
COPY store_sales FROM '/tmp/store_sales.dat' WITH DELIMITER '|' NULL AS '';

ANALYSE dbgen_version;
ANALYSE customer_address;
ANALYSE customer_demographics;
ANALYSE date_dim;
ANALYSE warehouse;
ANALYSE ship_mode;
ANALYSE time_dim;
ANALYSE reason;
ANALYSE income_band;
ANALYSE item;
ANALYSE store;
ANALYSE call_center;
ANALYSE customer;
ANALYSE web_site;
ANALYSE store_returns;
ANALYSE household_demographics;
ANALYSE web_page;
ANALYSE promotion;
ANALYSE catalog_page;
ANALYSE inventory;
ANALYSE catalog_returns;
ANALYSE web_returns;
ANALYSE web_sales;
ANALYSE catalog_sales;
ANALYSE store_sales;

